version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy-gh-pages:
    executor:
      name: node/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "28:13:40:e1:05:b5:e9:06:4c:12:e3:22:5c:32:a3:e9"
      - node/with-cache:
          steps:
            - run: npm install
            - run: git config --global user.email "marchsabio@gmail.com"
            - run: git config --global user.name "CI Circle Pipeline"
            - run: npm run deploy
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - deploy-gh-pages:
            filters:
              branches:
                only: master
